 
   let joke =  [ "Why don't scientists trust atoms? Because they make up everything!",
     "I'm reading a book on anti-gravity. It's impossible to put down!",
     "Why did the scarecrow win an award? Because he was outstanding in his field!",
     "I told my wife she was drawing her eyebrows too high. She looked surprised.",
     "Parallel lines have so much in common. It’s a shame they’ll never meet.",
     "What did one wall say to the other wall? I’ll meet you at the corner!",
     "Why did the bicycle fall over? Because it was two-tired!",
     "I'm on a whiskey diet. I've lost three days already!",
     "I used to play piano by ear, but now I use my hands.",
     "I'm reading a horror book in Braille. Something bad is going to happen. I can feel it.",
     "I'm trying to organize a hide and seek competition, but it's tough to find good players – they're always hiding!",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
     "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
     "Why did the tomato turn red? Because it saw the salad dressing!",
     "I told my wife she should embrace her mistakes. She gave me a hug.",
     "I'm reading a book on the history of glue. I just can't seem to put it down.",
     "Why don't skeletons fight each other? They don't have the guts.",
     "I'm trying to organize a space-themed party, but I just can't planet.",
     "Why did the chicken join a band? Because it had the drumsticks!",
     "I used to be a baker, but I couldn't make enough dough.",
     "Why did the tomato turn red? Because it saw the salad dressing!",
     "Why don't eggs tell jokes? Because they’d crack each other up!",
     "I'm reading a book about anti-gravity. It's impossible to put down!",
     "Why did the math book look sad? Because it had too many problems.",
     "Why did the bicycle fall over? Because it was two-tired!",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
     "I'm reading a book on the history of glue. I just can't seem to put it down.",
     "What did one ocean say to the other ocean? Nothing, they just waved!",
     "I told my wife she was drawing her eyebrows too high. She looked surprised.",
     "Why did the scarecrow win an award? Because he was outstanding in his field!",
     "Why don’t skeletons fight each other? They don’t have the guts!",
     "What did one wall say to the other wall? I’ll meet you at the corner!",
     "Parallel lines have so much in common. It’s a shame they’ll never meet.",
     "I'm on a whiskey diet. I've lost three days already!",
     "I used to play piano by ear, but now I use my hands.",
     "I'm reading a horror book in Braille. Something bad is going to happen. I can feel it.",
     "I'm trying to organize a hide and seek competition, but it's tough to find good players – they're always hiding!",
     "Why did the chicken join a band? Because it had the drumsticks!",
     "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
     "I told my wife she should embrace her mistakes. She gave me a hug.",
     "I'm trying to organize a space-themed party, but I just can't planet.",
     "I used to be a baker, but I couldn't make enough dough.",
     "Why did the math book look sad? Because it had too many problems.",
     "Why don't eggs tell jokes? Because they’d crack each other up!",
     "Why did the bicycle fall over? Because it was two-tired!",
     "I'm reading a book about anti-gravity. It's impossible to put down!",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
     "I'm reading a book on the history of glue. I just can't seem to put it down.",
     "Why did the scarecrow win an award? Because he was outstanding in his field!",
     "Why don’t skeletons fight each other? They don’t have the guts!",
     "What did one wall say to the other wall? I’ll meet you at the corner!",
     "Parallel lines have so much in common. It’s a shame they’ll never meet.",
     "I'm on a whiskey diet. I've lost three days already!",
     "I used to play piano by ear, but now I use my hands.",
     "I'm reading a horror book in Braille. Something bad is going to happen. I can feel it.",
     "I'm trying to organize a hide and seek competition, but it's tough to find good players – they're always hiding!",
     "Why did the chicken join a band? Because it had the drumsticks!",
     "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
     "I told my wife she should embrace her mistakes. She gave me a hug.",
     "I'm trying to organize a space-themed party, but I just can't planet.",
     "I used to be a baker, but I couldn't make enough dough.",
     "Why did the math book look sad? Because it had too many problems.",
     "Why don't eggs tell jokes? Because they’d crack each other up!",
     "Why did the bicycle fall over? Because it was two-tired!",
     "I'm reading a book about anti-gravity. It's impossible to put down!",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
     "I'm reading a book on the history of glue. I just can't seem to put it down.",
     "Why did the tomato turn red? Because it saw the salad dressing!",
     "I told my wife she was drawing her eyebrows too high. She looked surprised.",
     "Why did the scarecrow win an award? Because he was outstanding in his field!",
     "I'm trying to organize a hide and seek competition, but it's tough to find good players – they're always hiding!",
     "Why did the chicken join a band? Because it had the drumsticks!",
     "I'm reading a horror book in Braille. Something bad is going to happen. I can feel it.",
     "I'm on a whiskey diet. I've lost three days already!",
     "I used to play piano by ear, but now I use my hands.",
     "I'm reading a book about anti-gravity. It's impossible to put down!",
     "Why did the bicycle fall over? Because it was two-tired!",
     "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
     "Why did the tomato turn red? Because it saw the salad dressing!",
     "I told my wife she should embrace her mistakes. She gave me a hug.",
     "I'm trying to organize a space-themed party, but I just can't planet.",
     "Why did the math book look sad? Because it had too many problems.",
     "Why don't eggs tell jokes? Because they’d crack each other up!",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
     "I'm reading a book on the history of glue. I just can't seem to put it down.",
     "What did one ocean say to the other ocean? Nothing, they just waved!",
     "I told my wife she was drawing her eyebrows too high. She looked surprised.",
     "Why did the scarecrow win an award? Because he was outstanding in his field!",
     "Why don’t skeletons fight each other? They don’t have the guts!",
     "What did one wall say to the other wall? I’ll meet you at the corner!",
     "Parallel lines have so much in common. It’s a shame they’ll never meet.",
     "I'm on a whiskey diet. I've lost three days already!",
     "I used to play piano by ear, but now I use my hands.",
     "I'm reading a horror book in Braille. Something bad is going to happen. I can feel it.",
     "I'm trying to organize a hide and seek competition, but it's tough to find good players – they're always hiding!",
     "Why did the chicken join a band? Because it had the drumsticks!",
     "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
     "I told my wife she should embrace her mistakes. She gave me a hug.",
     "I'm trying to organize a space-themed party, but I just can't planet.",
     "I used to be a baker, but I couldn't make enough dough.",
     "Why did the math book look sad? Because it had too many problems.",
     "Why don't eggs tell jokes? Because they’d crack each other up!",
     "Why did the bicycle fall over? Because it was two-tired!",
     "I'm reading a book about anti-gravity. It's impossible to put down!",
     "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
     "I'm reading a book on the history of glue. I just can't seem to put it down.",]
   let randomNumber = Math.floor(Math.random ()*107)
 let node =  document.getElementById("demo");
  node.innerText=`"${joke[randomNumber]}"`

 
   